name: Client Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build client
        run: npm run build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: client-build
          path: dist/spa

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist/spa'
          destination-github-username: 'KonstantinSerebryakov'
          destination-repository-name: 'pyshop-server'
          user-email: KonstantinSerebryakov2000@gmail.com
          target-branch: main
          target-directory: 'client'
      # - name: Trigger Server Deployment
      #   uses: repo-sync/github-action@v2
      #   with:
      #     token: ${{ secrets.PAT }} # Personal Access Token with repo scope
      #     repository: "KonstantinSerebryakov/pyshop-server"
      #     event_type: deploy-trigger
      #     client_artifact: ${{ steps.build.outputs.client-build }}
